version: "3.9"

services:
  whisper-api:
    container_name: whisper-api
    build:
      context: .
      dockerfile: Dockerfile
    image: whisper-api:cuda
    ports:
      - "8005:8005"
    volumes:
      - ./models:/app/models
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Modern Compose v2+ syntax for GPU support
    runtime: nvidia
    networks:
      - shared-network
    restart: unless-stopped

networks:
  shared-network:
    external: true
    name: shared-tts-network
